#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-crfsuite
Version  : 0.9.6
Release  : 7
URL      : https://files.pythonhosted.org/packages/73/b5/d9640656386b28ca181410f292ffcc3f1c39d9438f0796f874fd5d65ee34/python-crfsuite-0.9.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/73/b5/d9640656386b28ca181410f292ffcc3f1c39d9438f0796f874fd5d65ee34/python-crfsuite-0.9.6.tar.gz
Summary  : Python binding for CRFsuite
Group    : Development/Tools
License  : MIT
Requires: python-crfsuite-python = %{version}-%{release}
Requires: python-crfsuite-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
python-crfsuite
        ===============

%package python
Summary: python components for the python-crfsuite package.
Group: Default
Requires: python-crfsuite-python3 = %{version}-%{release}

%description python
python components for the python-crfsuite package.


%package python3
Summary: python3 components for the python-crfsuite package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-crfsuite package.


%prep
%setup -q -n python-crfsuite-0.9.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542759629
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
